ARG NGINX_VERSION=alpine

FROM nginx:${NGINX_VERSION}


COPY services/nginx/configs/ /etc/nginx/configs/

COPY services/nginx/entrypoint.nginx.sh /usr/local/bin/entrypoint.sh
RUN sed -i 's/\r$//' /usr/local/bin/entrypoint.sh && chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
