include:
  - path: services/nginx/docker-compose.yml
    project_directory: .
    env_file: .env
  - path: services/node/docker-compose.yml
    project_directory: .
    env_file: .env

services:
  nginx:
    environment:
      - NGINX_CONF=${NGINX_CONF:-toolkit}
      - MCP_PORT=${MCP_PORT:-8933}
    depends_on:
      - node
